// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2zfu3UcX3r4jl5B9FVpcLRa5uifA8ZVs',
    appId: '1:625430764518:web:bd038a61081359309d5427',
    messagingSenderId: '625430764518',
    projectId: 'to-do-list-b263d',
    authDomain: 'to-do-list-b263d.firebaseapp.com',
    storageBucket: 'to-do-list-b263d.appspot.com',
    measurementId: 'G-MLCL1LND6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIP3GGC9zqYDAFHINZjRiH35YdMCNF1GE',
    appId: '1:625430764518:android:ccabdfc97a12bffc9d5427',
    messagingSenderId: '625430764518',
    projectId: 'to-do-list-b263d',
    storageBucket: 'to-do-list-b263d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnALXjQeLxmAdhksXaTZaIY-I-bNIXr4Y',
    appId: '1:625430764518:ios:d2b62b067c4a1a4f9d5427',
    messagingSenderId: '625430764518',
    projectId: 'to-do-list-b263d',
    storageBucket: 'to-do-list-b263d.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );
}
